---
name: from-device42

source:
  name: device42
  settings:
    url: "https://device42.example.com"
    username: "your-username"
    password: "your-password"
    verify_ssl: true

destination:
  name: infrahub
  settings:
    url: "http://localhost:8000"

order: [
  "BuiltinTag",
  "RoleGeneric", 
  "OrganizationGeneric",
  "LocationGeneric",
  "InfraRack",
  "ChoiceDeviceType",
  "InfraDevice",
  "InfraInterfaceL2L3",
]

schema_mapping:
  # Organizations (Customers in Device42)
  - name: OrganizationGeneric
    mapping: customers
    identifiers: ["name"]
    fields:
      - name: name
        mapping: name
      - name: description
        mapping: notes

  # Locations (Buildings in Device42)
  - name: LocationGeneric
    mapping: buildings
    identifiers: ["name"]
    fields:
      - name: name
        mapping: name
      - name: description
        mapping: notes
      - name: type
        static: "Building"

  # Locations (Rooms in Device42)  
  - name: LocationGeneric
    mapping: rooms
    identifiers: ["name"]
    fields:
      - name: name
        mapping: name
      - name: description
        mapping: notes
      - name: type
        static: "Room"

  # Racks
  - name: InfraRack
    mapping: racks
    identifiers: ["name", "location"]
    fields:
      - name: name
        mapping: name
      - name: location
        mapping: room
        reference: LocationGeneric
      - name: height
        mapping: size
      - name: serial_number
        mapping: serial_no
      - name: asset_tag
        mapping: asset_no

  # Hardware Models (Device Types)
  - name: ChoiceDeviceType  
    mapping: hardwares
    identifiers: ["name", "manufacturer"]
    fields:
      - name: name
        mapping: name
      - name: part_number
        mapping: part_no
      - name: height
        mapping: size
      - name: manufacturer
        mapping: manufacturer
        reference: OrganizationGeneric

  # Devices
  - name: InfraDevice
    identifiers: ["name"]
    mapping: devices
    fields:
      - name: name
        mapping: name
      - name: serial_number
        mapping: serial_no
      - name: asset_tag
        mapping: asset_no
      - name: description
        mapping: notes
      - name: model
        mapping: hardware
        reference: ChoiceDeviceType
      - name: organization
        mapping: customer
        reference: OrganizationGeneric
      - name: location
        mapping: room
        reference: LocationGeneric
      - name: rack
        mapping: rack
        reference: InfraRack
    transforms:
      - field: name
        expression: "{{ name.lower() if name else '' }}"

  # Network Interfaces (Device42 IP addresses often represent interfaces)
  - name: InfraInterfaceL2L3
    identifiers: ["device", "name"]
    mapping: ips
    fields:
      - name: name
        mapping: label
      - name: description  
        mapping: notes
      - name: device
        mapping: device
        reference: InfraDevice
    # Only include IPs that have interface-like labels
    filters:
      - field: label
        operation: "exists"
        value: true