---
# yaml-language-server: $schema=https://schema.infrahub.app/infrahub/schema/latest.json
version: '1.0'

nodes:
  - name: NetConntrackDialer
    namespace: Monitoring
    description: Aggregated Prometheus conntrack dialer metrics per dialer_name.
    label: Net Conntrack Dialer
    icon: mdi:lan-connect
    include_in_menu: true
    human_friendly_id: [dialer__value]
    display_labels: [dialer__value, status__value]
    order_by: [dialer__value]
    uniqueness_constraints:
      - [dialer__value]

    attributes:
      - name: dialer
        label: Dialer name
        kind: Text
        optional: false
        order_weight: 1000

      - name: status
        label: Status
        kind: Text              # keep Text; you can later migrate to a choice set if you have one
        optional: true
        default_value: unknown
        order_weight: 1100

      - name: established_rps
        label: Established (rps)
        kind: Number
        optional: true
        default_value: 0
        order_weight: 1200

      - name: closed_rps
        label: Closed (rps)
        kind: Number
        optional: true
        default_value: 0
        order_weight: 1300

      - name: failed_rps
        label: Failed (rps)
        kind: Number
        optional: true
        default_value: 0
        order_weight: 1400

      - name: failed_refused_rps
        label: Failed refused (rps)
        kind: Number
        optional: true
        default_value: 0
        order_weight: 1500

      - name: failed_resolution_rps
        label: Failed resolution (rps)
        kind: Number
        optional: true
        default_value: 0
        order_weight: 1600

      - name: failed_timeout_rps
        label: Failed timeout (rps)
        kind: Number
        optional: true
        default_value: 0
        order_weight: 1700

      - name: failed_unknown_rps
        label: Failed unknown (rps)
        kind: Number
        optional: true
        default_value: 0
        order_weight: 1800

      - name: attempts_rps
        label: Attempts (rps)
        kind: Number
        optional: true
        default_value: 0
        order_weight: 1900

      - name: success_rate
        label: Success rate (0..1)
        kind: Number
        optional: true
        default_value: 0
        parameters:
          min_value: 0
          max_value: 1
        order_weight: 2000

      - name: last_updated
        label: Last updated
        kind: DateTime
        optional: true
        order_weight: 2100

    relationships:
      - name: tags
        peer: BuiltinTag
        optional: true
        cardinality: many
        kind: Attribute
        order_weight: 3000
