---
name: network-monitor-sync
source:
  name: my_network_monitor
  settings:
    api_url: "https://monitoring.example.com/api/v1"
    api_key: "${NETWORK_MONITOR_API_KEY}"
    timeout: 30
destination:
  name: infrahub
  settings:
    url: "http://localhost:8000"
    token: "${INFRAHUB_TOKEN}"
    branch: "main"
order:
  - Device
  - Interface
schema_mapping:
  - name: Device
    mapping: devices
    identifiers:
      - name
    filters:
      - field: status
        operation: "=="
        value: "active"
  - name: Interface
    mapping: interfaces
    identifiers:
      - device
      - name
    filters:
      - field: status
        operation: "=="
        value: "up"