---
name: dotted-import-demo
source:
  adapter: "adapters.my_network:MyNetworkAdapter"  # Dotted import path
  settings:
    api_endpoint: "https://network-api.example.com"
destination:
  adapter: "./adapters/custom_infrahub.py:CustomInfrahubAdapter"  # Local file
  settings:
    url: "http://localhost:8000"
    token: "${INFRAHUB_TOKEN}"
order:
  - NetworkDevice
schema_mapping:
  - name: NetworkDevice
    mapping: devices