---
name: from-peeringdb
source:
  name: genericrestapi
  settings:
    url: "https://www.peeringdb.com"
    api_endpoint: "api"
    auth_method: "none"          # PeeringDB allows public access (beware rate limits)
    response_key_pattern: "data"  # PeeringDB wraps lists under "data"


destination:
  name: infrahub
  settings:
    url: "http://localhost:8000"

# Optional: Skip objects in the source that don't exist in the destination (prevents creation)
dyffsync_flags: ["SKIP_UNMATCHED_SRC"]

order: ["InfraAutonomousSystem"]

schema_mapping:
  - name: InfraAutonomousSystem
    mapping: net                # PeeringDB resource
    identifiers: ["asn"]        # needed to match/merge objects
    fields:
      - name: asn               # minimal id field
        mapping: asn
      - name: name
        mapping: name
      - name: irr_as_set
        mapping: irr_as_set
      - name: ipv4_max_prefixes
        mapping: info_prefixes4
      - name: ipv6_max_prefixes
        mapping: info_prefixes6
